### ISSUE TITLE
Is History broken?

### ISSUE THREAD

**Issue by coreyhaines** [veezus/vurl#1]
No link to history on main page, when I go to URL, I don't see it

**Comment by veezus** [comment]
Your user id has probably changed. I will look at this tonight. There's a bunch of undeployed code around users that would have let you look into this on your own.

**Comment by coreyhaines** [comment]
ok, thanks. I was going to fork and look, but just wanted to leave this as a note for future reference. I'm traveling a lot over the next week, so I might be able to look at it on a plane, or when I get back. No huge rush, although I do use it a lot to stroke my already inflated ego. :)
